### ISSUE TITLE
Copying

### ISSUE THREAD

**Issue by possibilities** [ianliu/tdphsk#1]
OK to do some experiments based on this? I especially like the hotswap sockets + handwiring canals.

**Comment by possibilities** [comment]
Also VERY cool project, thanks for sharing it! I'm learning a lot

**Comment by ianliu** [comment]
Hey! Forgot to put a license, will do! You are OK to do any experiments you want :P

**Comment by ianliu** [comment]
The project is now GPLv3, as per commit 1b0fd46546710568e86995cc3e15cd186e3bcec4
